### ISSUE TITLE
GitHub dry

### ISSUE THREAD

**Issue by fart-master** [blur-network/dpow-blur#16]
All the last commits are updates to the readme and other trivial things. When is this expected to launch?

**Comment by who-biz** [comment]
Soon. You’re able to see our channel in the KMD discord. You have read about our progress, there.

**Comment by who-biz** [comment]
Also, for anyone reading... our active development is taking place on the `testnet` branch.  After work is pushed to that branch, it is pushed to default once tested.

Re-opening this issue, for visibility

**Comment by who-biz** [comment]
Closing since `testnet` branch is now default.
